using System;
using UnityEngine;
using UnityEngine.InputSystem;

/// <summary>
/// Acts as the central broadcaster for raw input events generated by 
/// the Unity Input System.
/// </summary>
public class InputManager : MonoBehaviour
{
    /// <summary>
    /// Singleton instance of the InputManager.
    /// </summary>
    public static InputManager Instance { get; private set; }

    public static event Action<Vector2> onMove;
    public static event Action<Vector2> onAim;
    public static event Action onAttackStarted;
    public static event Action onAttackCanceled;
    public static event Action onAbilityStarted;
    public static event Action onDodgeStarted;
    public static event Action onInteractStarted;
    public static event Action<Vector2> onCameraRotate;
    public static event Action onCameraRotateToggleStarted;
    public static event Action onCameraRotateToggleCanceled;
    public static event Action<Vector2> onCameraZoom;
    public static event Action onToggleHandViewStarted;

    private @InputActions _actions;

    private void Awake()
    {
        if (Instance != null && Instance != this)
        {
            Destroy(gameObject);
            return;
        }
        Instance = this;

        _actions = new @InputActions();
    }

    private void OnEnable()
    {
        SubscribeToActions();
        EnablePlayerControls();
    }

    private void OnDisable()
    {
        UnsubscribeFromActions();
        DisableAllControls();
    }

    private void Update()
    {
        if (_actions.Player.enabled)
        {
            onAim?.Invoke(
                _actions.Player.Aim.ReadValue<Vector2>());
            onCameraRotate?.Invoke(
                _actions.Player.CameraRotate.ReadValue<Vector2>());
        }
    }

    /// <summary>
    /// Enables the action maps related to player movement and global 
    /// UI shortcuts.
    /// </summary>
    public void EnablePlayerControls()
    {
        _actions.Player.Enable();
        _actions.Global.Enable();
        Cursor.lockState = CursorLockMode.Confined;
        Cursor.visible = true;
    }

    /// <summary>
    /// Disables the action maps related to player movement.
    /// </summary>
    public void DisablePlayerControls()
    {
        _actions.Player.Disable();
        Cursor.lockState = CursorLockMode.None;
        Cursor.visible = true;
    }

    private void DisableAllControls()
    {
        _actions.Player.Disable();
        _actions.Global.Disable();
    }

    private void SubscribeToActions()
    {
        _actions.Player.Move.performed +=
            ctx => onMove?.Invoke(ctx.ReadValue<Vector2>());
        _actions.Player.Move.canceled +=
            ctx => onMove?.Invoke(Vector2.zero);

        _actions.Player.Attack.started +=
            ctx => onAttackStarted?.Invoke();
        _actions.Player.Attack.canceled +=
            ctx => onAttackCanceled?.Invoke();

        _actions.Player.Ability.started +=
            ctx => onAbilityStarted?.Invoke();
        _actions.Player.Dodge.started +=
            ctx => onDodgeStarted?.Invoke();
        _actions.Player.Interact.started +=
            ctx => onInteractStarted?.Invoke();

        _actions.Player.CameraRotateToggle.started +=
            ctx => onCameraRotateToggleStarted?.Invoke();
        _actions.Player.CameraRotateToggle.canceled +=
            ctx => onCameraRotateToggleCanceled?.Invoke();

        _actions.Player.CameraZoom.performed +=
            ctx => onCameraZoom?.Invoke(ctx.ReadValue<Vector2>());

        _actions.Global.ToggleHandView.started +=
            ctx => onToggleHandViewStarted?.Invoke();
    }

    private void UnsubscribeFromActions()
    {
        onMove = null;
        onAim = null;
        onAttackStarted = null;
        onAttackCanceled = null;
        onAbilityStarted = null;
        onDodgeStarted = null;
        onInteractStarted = null;
        onCameraRotate = null;
        onCameraRotateToggleStarted = null;
        onCameraRotateToggleCanceled = null;
        onCameraZoom = null;
        onToggleHandViewStarted = null;
    }
}